# Generated by Django 6.1.1 on 2026-09-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='organizations.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='customers.customer')),
            ],
            options={
                'ordering': ['company', 'contract_number'],
            },
        ),
        migrations.CreateModel(
            name='ContractService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('included_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_services', to='contracts.contract')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_services', to='services.service')),
            ],
            options={
                'ordering': ['contract', 'service'],
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('response_time_minutes', models.PositiveIntegerField(help_text='Maximum allowed time to respond to a ticket.')),
                ('resolution_time_minutes', models.PositiveIntegerField(help_text='Maximum allowed time to resolve a ticket.')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='contracts.contract')),
            ],
            options={
                'ordering': ['contract', 'priority', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('company', 'contract_number'), name='unique_contract_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='contractservice',
            constraint=models.UniqueConstraint(fields=('contract', 'service'), name='unique_service_per_contract'),
        ),
    ]
