# Generated by Django 6.1.1 on 2026-09-30 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequirement',
            options={'ordering': ['service', 'requirement_type']},
        ),
        migrations.RemoveField(
            model_name='servicerequirement',
            name='name',
        ),
        migrations.AddField(
            model_name='servicerequirement',
            name='certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requirements', to='skills.certification'),
        ),
        migrations.AddField(
            model_name='servicerequirement',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requirements', to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='servicerequirement',
            name='minimum_proficiency',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Required proficiency level from 1 to 5. Used for skills.', null=True),
        ),
    ]
